/**
 * generated by Xtext 2.10.0
 */
package org.xtext.compilation.whileComp.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.compilation.whileComp.Expr;
import org.xtext.compilation.whileComp.ExprEq;
import org.xtext.compilation.whileComp.ExprSimple;
import org.xtext.compilation.whileComp.WhileCompPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expr Eq</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compilation.whileComp.impl.ExprEqImpl#getExprSimple1 <em>Expr Simple1</em>}</li>
 *   <li>{@link org.xtext.compilation.whileComp.impl.ExprEqImpl#getExprSimple2 <em>Expr Simple2</em>}</li>
 *   <li>{@link org.xtext.compilation.whileComp.impl.ExprEqImpl#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExprEqImpl extends MinimalEObjectImpl.Container implements ExprEq
{
  /**
   * The cached value of the '{@link #getExprSimple1() <em>Expr Simple1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprSimple1()
   * @generated
   * @ordered
   */
  protected ExprSimple exprSimple1;

  /**
   * The cached value of the '{@link #getExprSimple2() <em>Expr Simple2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExprSimple2()
   * @generated
   * @ordered
   */
  protected ExprSimple exprSimple2;

  /**
   * The cached value of the '{@link #getExpr() <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpr()
   * @generated
   * @ordered
   */
  protected Expr expr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExprEqImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return WhileCompPackage.Literals.EXPR_EQ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExprSimple getExprSimple1()
  {
    return exprSimple1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprSimple1(ExprSimple newExprSimple1, NotificationChain msgs)
  {
    ExprSimple oldExprSimple1 = exprSimple1;
    exprSimple1 = newExprSimple1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1, oldExprSimple1, newExprSimple1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExprSimple1(ExprSimple newExprSimple1)
  {
    if (newExprSimple1 != exprSimple1)
    {
      NotificationChain msgs = null;
      if (exprSimple1 != null)
        msgs = ((InternalEObject)exprSimple1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1, null, msgs);
      if (newExprSimple1 != null)
        msgs = ((InternalEObject)newExprSimple1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1, null, msgs);
      msgs = basicSetExprSimple1(newExprSimple1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1, newExprSimple1, newExprSimple1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExprSimple getExprSimple2()
  {
    return exprSimple2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExprSimple2(ExprSimple newExprSimple2, NotificationChain msgs)
  {
    ExprSimple oldExprSimple2 = exprSimple2;
    exprSimple2 = newExprSimple2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2, oldExprSimple2, newExprSimple2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExprSimple2(ExprSimple newExprSimple2)
  {
    if (newExprSimple2 != exprSimple2)
    {
      NotificationChain msgs = null;
      if (exprSimple2 != null)
        msgs = ((InternalEObject)exprSimple2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2, null, msgs);
      if (newExprSimple2 != null)
        msgs = ((InternalEObject)newExprSimple2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2, null, msgs);
      msgs = basicSetExprSimple2(newExprSimple2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2, newExprSimple2, newExprSimple2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expr getExpr()
  {
    return expr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExpr(Expr newExpr, NotificationChain msgs)
  {
    Expr oldExpr = expr;
    expr = newExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR, oldExpr, newExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExpr(Expr newExpr)
  {
    if (newExpr != expr)
    {
      NotificationChain msgs = null;
      if (expr != null)
        msgs = ((InternalEObject)expr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR, null, msgs);
      if (newExpr != null)
        msgs = ((InternalEObject)newExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - WhileCompPackage.EXPR_EQ__EXPR, null, msgs);
      msgs = basicSetExpr(newExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, WhileCompPackage.EXPR_EQ__EXPR, newExpr, newExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1:
        return basicSetExprSimple1(null, msgs);
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2:
        return basicSetExprSimple2(null, msgs);
      case WhileCompPackage.EXPR_EQ__EXPR:
        return basicSetExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1:
        return getExprSimple1();
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2:
        return getExprSimple2();
      case WhileCompPackage.EXPR_EQ__EXPR:
        return getExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1:
        setExprSimple1((ExprSimple)newValue);
        return;
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2:
        setExprSimple2((ExprSimple)newValue);
        return;
      case WhileCompPackage.EXPR_EQ__EXPR:
        setExpr((Expr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1:
        setExprSimple1((ExprSimple)null);
        return;
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2:
        setExprSimple2((ExprSimple)null);
        return;
      case WhileCompPackage.EXPR_EQ__EXPR:
        setExpr((Expr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE1:
        return exprSimple1 != null;
      case WhileCompPackage.EXPR_EQ__EXPR_SIMPLE2:
        return exprSimple2 != null;
      case WhileCompPackage.EXPR_EQ__EXPR:
        return expr != null;
    }
    return super.eIsSet(featureID);
  }

} //ExprEqImpl
