/*
 * generated by Xtext 2.10.0
 */
package esir.compilation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhileCompScopeProvider extends DelegatingScopeProvider {
}
