/**
 * generated by Xtext 2.10.0
 */
package org.xtext.validation;

import org.xtext.validation.AbstractCompilationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CompilationValidator extends AbstractCompilationValidator {
}
