/**
 * generated by Xtext 2.10.0
 */
package esir.compilation.validation;

import esir.compilation.validation.AbstractWhileCompValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WhileCompValidator extends AbstractWhileCompValidator {
}
