/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.test;

import org.xtext.example.test.AbstractMyDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
