/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.test.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nop</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.test.myDsl.MyDslPackage#getNop()
 * @model
 * @generated
 */
public interface Nop extends Command
{
} // Nop
