/*
 * generated by Xtext 2.10.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalCompilationParser;
import org.xtext.services.CompilationGrammarAccess;

public class CompilationParser extends AbstractAntlrParser {

	@Inject
	private CompilationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCompilationParser createParser(XtextTokenStream stream) {
		return new InternalCompilationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public CompilationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CompilationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
