/*
 * generated by Xtext 2.10.0
 */
package org.xtext.compilation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhileCompStandaloneSetup extends WhileCompStandaloneSetupGenerated {

	def static void doSetup() {
		new WhileCompStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
