/**
 * generated by Xtext 2.10.0
 */
package esir.compilation.whileComp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expr Simple</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getValeur <em>Valeur</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getOpe <em>Ope</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getLexpr <em>Lexpr</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getExpr <em>Expr</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getN <em>N</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getEx1 <em>Ex1</em>}</li>
 *   <li>{@link esir.compilation.whileComp.ExprSimple#getEx2 <em>Ex2</em>}</li>
 * </ul>
 * </p>
 *
 * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple()
 * @model
 * @generated
 */
public interface ExprSimple extends EObject
{
  /**
   * Returns the value of the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valeur</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valeur</em>' attribute.
   * @see #setValeur(String)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Valeur()
   * @model
   * @generated
   */
  String getValeur();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getValeur <em>Valeur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Valeur</em>' attribute.
   * @see #getValeur()
   * @generated
   */
  void setValeur(String value);

  /**
   * Returns the value of the '<em><b>Ope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ope</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ope</em>' attribute.
   * @see #setOpe(String)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Ope()
   * @model
   * @generated
   */
  String getOpe();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getOpe <em>Ope</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ope</em>' attribute.
   * @see #getOpe()
   * @generated
   */
  void setOpe(String value);

  /**
   * Returns the value of the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lexpr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lexpr</em>' containment reference.
   * @see #setLexpr(Lexpr)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Lexpr()
   * @model containment="true"
   * @generated
   */
  Lexpr getLexpr();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getLexpr <em>Lexpr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lexpr</em>' containment reference.
   * @see #getLexpr()
   * @generated
   */
  void setLexpr(Lexpr value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expr)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Expr()
   * @model containment="true"
   * @generated
   */
  Expr getExpr();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expr value);

  /**
   * Returns the value of the '<em><b>N</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>N</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' containment reference.
   * @see #setN(Not)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_N()
   * @model containment="true"
   * @generated
   */
  Not getN();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getN <em>N</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' containment reference.
   * @see #getN()
   * @generated
   */
  void setN(Not value);

  /**
   * Returns the value of the '<em><b>Ex1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ex1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex1</em>' containment reference.
   * @see #setEx1(Expr)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Ex1()
   * @model containment="true"
   * @generated
   */
  Expr getEx1();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getEx1 <em>Ex1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex1</em>' containment reference.
   * @see #getEx1()
   * @generated
   */
  void setEx1(Expr value);

  /**
   * Returns the value of the '<em><b>Ex2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ex2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ex2</em>' containment reference.
   * @see #setEx2(Expr)
   * @see esir.compilation.whileComp.WhileCompPackage#getExprSimple_Ex2()
   * @model containment="true"
   * @generated
   */
  Expr getEx2();

  /**
   * Sets the value of the '{@link esir.compilation.whileComp.ExprSimple#getEx2 <em>Ex2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ex2</em>' containment reference.
   * @see #getEx2()
   * @generated
   */
  void setEx2(Expr value);

} // ExprSimple
