/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.compilation.ui.internal.CompilationActivator;

public class CompilationUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CompilationActivator.getInstance().getInjector("org.xtext.Compilation");
	}

}
