/**
 * generated by Xtext 2.10.0
 */
package org.xtext.compilation.whileComp;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cons</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.compilation.whileComp.Cons#getCons <em>Cons</em>}</li>
 * </ul>
 *
 * @see org.xtext.compilation.whileComp.WhileCompPackage#getCons()
 * @model
 * @generated
 */
public interface Cons extends EObject
{
  /**
   * Returns the value of the '<em><b>Cons</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cons</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cons</em>' attribute.
   * @see #setCons(String)
   * @see org.xtext.compilation.whileComp.WhileCompPackage#getCons_Cons()
   * @model
   * @generated
   */
  String getCons();

  /**
   * Sets the value of the '{@link org.xtext.compilation.whileComp.Cons#getCons <em>Cons</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cons</em>' attribute.
   * @see #getCons()
   * @generated
   */
  void setCons(String value);

} // Cons
